# Generated by Django 4.0.5 on 2022-06-13 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(help_text='Company ID', primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(help_text='Recruit ID', primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('skill', models.CharField(max_length=10)),
                ('recruit_compensation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='recruitment.company')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit', to='recruitment.recruit')),
            ],
        ),
    ]
