# Generated by Django 4.0.5 on 2022-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('skill', models.CharField(max_length=10)),
                ('recruit_compensation', models.IntegerField()),
            ],
        ),
    ]
