# Generated by Django 4.0.5 on 2022-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=10)),
                ('recruit_content', models.TextField()),
                ('recruit_position', models.CharField(max_length=20)),
                ('recruit_compensation', models.IntegerField()),
                ('skill', models.CharField(max_length=10)),
            ],
        ),
    ]
